# Generated by Django 3.2.16 on 2022-12-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasputin', '0002_auto_20221213_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
